// <auto-generated/>
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace Parquet.Thrift
{

  /// <summary>
  /// Description for ColumnIndex.
  /// Each <array-field>[i] refers to the page at OffsetIndex.page_locations[i]
  /// </summary>
  public partial class ColumnIndex : TBase
  {
    private List<long> _null_counts;

    /// <summary>
    /// A list of Boolean values to determine the validity of the corresponding
    /// min and max values. If true, a page contains only null values, and writers
    /// have to set the corresponding entries in min_values and max_values to
    /// byte[0], so that all lists have the same length. If false, the
    /// corresponding entries in min_values and max_values must be valid.
    /// </summary>
    public List<bool> Null_pages { get; set; }

    /// <summary>
    /// Two lists containing lower and upper bounds for the values of each page.
    /// These may be the actual minimum and maximum values found on a page, but
    /// can also be (more compact) values that do not exist on a page. For
    /// example, instead of storing ""Blart Versenwald III", a writer may set
    /// min_values[i]="B", max_values[i]="C". Such more compact values must still
    /// be valid values within the column's logical type. Readers must make sure
    /// that list entries are populated before using them by inspecting null_pages.
    /// </summary>
    public List<byte[]> Min_values { get; set; }

    public List<byte[]> Max_values { get; set; }

    /// <summary>
    /// Stores whether both min_values and max_values are orderd and if so, in
    /// which direction. This allows readers to perform binary searches in both
    /// lists. Readers cannot assume that max_values[i] <= min_values[i+1], even
    /// if the lists are ordered.
    /// 
    /// <seealso cref="BoundaryOrder"/>
    /// </summary>
    public BoundaryOrder Boundary_order { get; set; }

    /// <summary>
    /// A list containing the number of null values for each page *
    /// </summary>
    public List<long> Null_counts
    {
      get
      {
        return _null_counts;
      }
      set
      {
        __isset.null_counts = true;
        this._null_counts = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool null_counts;
    }

    public ColumnIndex()
    {
    }

    public ColumnIndex(List<bool> null_pages, List<byte[]> min_values, List<byte[]> max_values, BoundaryOrder boundary_order) : this()
    {
      this.Null_pages = null_pages;
      this.Min_values = min_values;
      this.Max_values = max_values;
      this.Boundary_order = boundary_order;
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_null_pages = false;
        bool isset_min_values = false;
        bool isset_max_values = false;
        bool isset_boundary_order = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  Null_pages = new List<bool>();
                  TList _list28 = await iprot.ReadListBeginAsync(cancellationToken);
                  for(int _i29 = 0; _i29 < _list28.Count; ++_i29)
                  {
                    bool _elem30;
                    _elem30 = await iprot.ReadBoolAsync(cancellationToken);
                    Null_pages.Add(_elem30);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_null_pages = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.List)
              {
                {
                  Min_values = new List<byte[]>();
                  TList _list31 = await iprot.ReadListBeginAsync(cancellationToken);
                  for(int _i32 = 0; _i32 < _list31.Count; ++_i32)
                  {
                    byte[] _elem33;
                    _elem33 = await iprot.ReadBinaryAsync(cancellationToken);
                    Min_values.Add(_elem33);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_min_values = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.List)
              {
                {
                  Max_values = new List<byte[]>();
                  TList _list34 = await iprot.ReadListBeginAsync(cancellationToken);
                  for(int _i35 = 0; _i35 < _list34.Count; ++_i35)
                  {
                    byte[] _elem36;
                    _elem36 = await iprot.ReadBinaryAsync(cancellationToken);
                    Max_values.Add(_elem36);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
                isset_max_values = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.I32)
              {
                Boundary_order = (BoundaryOrder)await iprot.ReadI32Async(cancellationToken);
                isset_boundary_order = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.List)
              {
                {
                  Null_counts = new List<long>();
                  TList _list37 = await iprot.ReadListBeginAsync(cancellationToken);
                  for(int _i38 = 0; _i38 < _list37.Count; ++_i38)
                  {
                    long _elem39;
                    _elem39 = await iprot.ReadI64Async(cancellationToken);
                    Null_counts.Add(_elem39);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_null_pages)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_min_values)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_max_values)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
        if (!isset_boundary_order)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("ColumnIndex");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        field.Name = "null_pages";
        field.Type = TType.List;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Bool, Null_pages.Count), cancellationToken);
          foreach (bool _iter40 in Null_pages)
          {
            await oprot.WriteBoolAsync(_iter40, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "min_values";
        field.Type = TType.List;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, Min_values.Count), cancellationToken);
          foreach (byte[] _iter41 in Min_values)
          {
            await oprot.WriteBinaryAsync(_iter41, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "max_values";
        field.Type = TType.List;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.String, Max_values.Count), cancellationToken);
          foreach (byte[] _iter42 in Max_values)
          {
            await oprot.WriteBinaryAsync(_iter42, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
        field.Name = "boundary_order";
        field.Type = TType.I32;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async((int)Boundary_order, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if (Null_counts != null && __isset.null_counts)
        {
          field.Name = "null_counts";
          field.Type = TType.List;
          field.ID = 5;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          {
            await oprot.WriteListBeginAsync(new TList(TType.I64, Null_counts.Count), cancellationToken);
            foreach (long _iter43 in Null_counts)
            {
              await oprot.WriteI64Async(_iter43, cancellationToken);
            }
            await oprot.WriteListEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString()
    {
      var sb = new StringBuilder("ColumnIndex(");
      sb.Append(", Null_pages: ");
      sb.Append(Null_pages);
      sb.Append(", Min_values: ");
      sb.Append(Min_values);
      sb.Append(", Max_values: ");
      sb.Append(Max_values);
      sb.Append(", Boundary_order: ");
      sb.Append(Boundary_order);
      if (Null_counts != null && __isset.null_counts)
      {
        sb.Append(", Null_counts: ");
        sb.Append(Null_counts);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
