// <auto-generated/>
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace Parquet.Thrift
{

  public partial class ColumnChunk : TBase
  {
    private string _file_path;
    private ColumnMetaData _meta_data;
    private long _offset_index_offset;
    private int _offset_index_length;
    private long _column_index_offset;
    private int _column_index_length;

    /// <summary>
    /// File where column data is stored.  If not set, assumed to be same file as
    /// metadata.  This path is relative to the current file.
    /// 
    /// </summary>
    public string File_path
    {
      get
      {
        return _file_path;
      }
      set
      {
        __isset.file_path = true;
        this._file_path = value;
      }
    }

    /// <summary>
    /// Byte offset in file_path to the ColumnMetaData *
    /// </summary>
    public long File_offset { get; set; }

    /// <summary>
    /// Column metadata for this chunk. This is the same content as what is at
    /// file_path/file_offset.  Having it here has it replicated in the file
    /// metadata.
    /// 
    /// </summary>
    public ColumnMetaData Meta_data
    {
      get
      {
        return _meta_data;
      }
      set
      {
        __isset.meta_data = true;
        this._meta_data = value;
      }
    }

    /// <summary>
    /// File offset of ColumnChunk's OffsetIndex *
    /// </summary>
    public long Offset_index_offset
    {
      get
      {
        return _offset_index_offset;
      }
      set
      {
        __isset.offset_index_offset = true;
        this._offset_index_offset = value;
      }
    }

    /// <summary>
    /// Size of ColumnChunk's OffsetIndex, in bytes *
    /// </summary>
    public int Offset_index_length
    {
      get
      {
        return _offset_index_length;
      }
      set
      {
        __isset.offset_index_length = true;
        this._offset_index_length = value;
      }
    }

    /// <summary>
    /// File offset of ColumnChunk's ColumnIndex *
    /// </summary>
    public long Column_index_offset
    {
      get
      {
        return _column_index_offset;
      }
      set
      {
        __isset.column_index_offset = true;
        this._column_index_offset = value;
      }
    }

    /// <summary>
    /// Size of ColumnChunk's ColumnIndex, in bytes *
    /// </summary>
    public int Column_index_length
    {
      get
      {
        return _column_index_length;
      }
      set
      {
        __isset.column_index_length = true;
        this._column_index_length = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool file_path;
      public bool meta_data;
      public bool offset_index_offset;
      public bool offset_index_length;
      public bool column_index_offset;
      public bool column_index_length;
    }

    public ColumnChunk()
    {
    }

    public ColumnChunk(long file_offset) : this()
    {
      this.File_offset = file_offset;
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_file_offset = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                File_path = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I64)
              {
                File_offset = await iprot.ReadI64Async(cancellationToken);
                isset_file_offset = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Struct)
              {
                Meta_data = new ColumnMetaData();
                await Meta_data.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.I64)
              {
                Offset_index_offset = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.I32)
              {
                Offset_index_length = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 6:
              if (field.Type == TType.I64)
              {
                Column_index_offset = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 7:
              if (field.Type == TType.I32)
              {
                Column_index_length = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_file_offset)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("ColumnChunk");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (File_path != null && __isset.file_path)
        {
          field.Name = "file_path";
          field.Type = TType.String;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(File_path, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        field.Name = "file_offset";
        field.Type = TType.I64;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(File_offset, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
        if (Meta_data != null && __isset.meta_data)
        {
          field.Name = "meta_data";
          field.Type = TType.Struct;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await Meta_data.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.offset_index_offset)
        {
          field.Name = "offset_index_offset";
          field.Type = TType.I64;
          field.ID = 4;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(Offset_index_offset, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.offset_index_length)
        {
          field.Name = "offset_index_length";
          field.Type = TType.I32;
          field.ID = 5;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI32Async(Offset_index_length, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.column_index_offset)
        {
          field.Name = "column_index_offset";
          field.Type = TType.I64;
          field.ID = 6;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(Column_index_offset, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.column_index_length)
        {
          field.Name = "column_index_length";
          field.Type = TType.I32;
          field.ID = 7;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI32Async(Column_index_length, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString()
    {
      var sb = new StringBuilder("ColumnChunk(");
      bool __first = true;
      if (File_path != null && __isset.file_path)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("File_path: ");
        sb.Append(File_path);
      }
      if(!__first) { sb.Append(", "); }
      sb.Append("File_offset: ");
      sb.Append(File_offset);
      if (Meta_data != null && __isset.meta_data)
      {
        sb.Append(", Meta_data: ");
        sb.Append(Meta_data== null ? "<null>" : Meta_data.ToString());
      }
      if (__isset.offset_index_offset)
      {
        sb.Append(", Offset_index_offset: ");
        sb.Append(Offset_index_offset);
      }
      if (__isset.offset_index_length)
      {
        sb.Append(", Offset_index_length: ");
        sb.Append(Offset_index_length);
      }
      if (__isset.column_index_offset)
      {
        sb.Append(", Column_index_offset: ");
        sb.Append(Column_index_offset);
      }
      if (__isset.column_index_length)
      {
        sb.Append(", Column_index_length: ");
        sb.Append(Column_index_length);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
